### ISSUE TITLE
Flake8 Errors for UI.py

### ISSUE THREAD

**Issue by ceduze** [ryanbae89/news_analyzer#4]
news-article-nlp/libraries/UI.py:8:80: E501 line too long (97 > 79 characters)
news-article-nlp/libraries/UI.py:26:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/UI.py:37:1: E305 expected 2 blank lines after class or function definition, found 1
news-article-nlp/libraries/UI.py:41:18: E265 block comment should start with '# '
news-article-nlp/libraries/UI.py:45:5: E265 block comment should start with '# '
news-article-nlp/libraries/UI.py:46:5: E265 block comment should start with '# '
news-article-nlp/libraries/UI.py:55:13: E265 block comment should start with '# '
news-article-nlp/libraries/UI.py:55:80: E501 line too long (84 > 79 characters)
news-article-nlp/libraries/UI.py:71:3: E261 at least two spaces before inline comment
news-article-nlp/libraries/UI.py:71:3: E262 inline comment should start with '# '
news-article-nlp/libraries/UI.py:74:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/UI.py:78:1: E304 blank lines found after function decorator
news-article-nlp/libraries/UI.py:81:5: W191 indentation contains tabs
news-article-nlp/libraries/UI.py:81:5: E101 indentation contains mixed spaces and tabs
news-article-nlp/libraries/UI.py:82:5: W191 indentation contains tabs
news-article-nlp/libraries/UI.py:82:5: E101 indentation contains mixed spaces and tabs
news-article-nlp/libraries/UI.py:92:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/UI.py:96:1: E304 blank lines found after function decorator
news-article-nlp/libraries/UI.py:97:80: E501 line too long (84 > 79 characters)
news-article-nlp/libraries/UI.py:99:5: W191 indentation contains tabs
news-article-nlp/libraries/UI.py:99:5: E101 indentation contains mixed spaces and tabs
news-article-nlp/libraries/UI.py:100:5: W191 indentation contains tabs
news-article-nlp/libraries/UI.py:100:5: E101 indentation contains mixed spaces and tabs
news-article-nlp/libraries/UI.py:105:80: E501 line too long (100 > 79 characters)
news-article-nlp/libraries/UI.py:107:80: E501 line too long (99 > 79 characters)
news-article-nlp/libraries/UI.py:109:80: E501 line too long (99 > 79 characters)
news-article-nlp/libraries/UI.py:118:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/UI.py:122:1: E304 blank lines found after function decorator
news-article-nlp/libraries/UI.py:125:5: W191 indentation contains tabs
news-article-nlp/libraries/UI.py:125:5: E101 indentation contains mixed spaces and tabs
news-article-nlp/libraries/UI.py:126:5: W191 indentation contains tabs
news-article-nlp/libraries/UI.py:126:5: E101 indentation contains mixed spaces and tabs
news-article-nlp/libraries/UI.py:136:1: E302 expected 2 blank lines, found 1
news-article-nlp/libraries/UI.py:140:1: E304 blank lines found after function decorator
news-article-nlp/libraries/UI.py:143:5: W191 indentation contains tabs
news-article-nlp/libraries/UI.py:143:5: E101 indentation contains mixed spaces and tabs
news-article-nlp/libraries/UI.py:144:5: W191 indentation contains tabs
news-article-nlp/libraries/UI.py:144:5: E101 indentation contains mixed spaces and tabs
news-article-nlp/libraries/UI.py:148:80: E501 line too long (82 > 79 characters)
news-article-nlp/libraries/UI.py:154:80: E501 line too long (91 > 79 characters)
news-article-nlp/libraries/UI.py:155:80: E501 line too long (89 > 79 characters)
news-article-nlp/libraries/UI.py:158:80: E501 line too long (94 > 79 characters)

**Comment by pcwright1** [comment]
I fixed all the flake8 issues. There are some remaining pylint issues that I don't know how to deal with. I posted to slack, haven't heard anything from anyone.

example:
E: 60,12: Module 'dash_html_components' has no 'H6' member (no-member)

I'm going to keep this open but the I think we are in a good spot with this issue.
